site_name: IT Operations Runbook
site_description: Operational runbook for infrastructure and deployment
site_author: MilesChristi
site_url: https://mileschristi.github.io/runbook/

theme:
  name: material
  language: fr
  custom_dir: docs/overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: grey
      accent: light blue
features:
  - navigation.tracking
  - navigation.sections
  - navigation.top
  # - navigation.expand   <-- doit être absent
  - toc.follow
  - search.highlight
  - search.suggest
  - content.code.copy
  - navigation.path

nav:
  - "Accueil": index.md

  - "Architecture":
      - "Vue d’ensemble": architecture/index.md

  - "Installations":
      - "Vue d’ensemble": installations/index.md

  - "Exploitation":
      - "Vue d’ensemble": exploitation/index.md

  - "Dépannage":
      - "Vue d’ensemble": depannage/index.md

  - "Checklists":
      - "Vue d’ensemble": checklists/index.md

  - "Incidents":
      - "Vue d’ensemble": incidents/index.md

  - "Scripts":
      - "Vue d’ensemble": scripts/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji

extra_css:
  - stylesheets/extra.css